[package]
name = "demo"
version = "0.1.0"
authors = ["Serge Vakulenko <serge.vakulenko@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.3.0" }
log = "0.4"
simple_logger = "1.13"
