[package]
name = "demo"
version = "0.1.0"
authors = ["Serge Vakulenko <serge.vakulenko@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { version = "0.3.0" }
iced_native = "0.4.0"
iced_graphics = "0.2.0"
log = "0.4"
env_logger = "0.9"
